inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 140
  Exclude:
    - 'app/components/**/*.rb'
    - 'spec/models/message_spec.rb'
    - 'spec/vcr_setup.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'config/routes.rb'
