---
- name: Debug
  debug:
    msg: "Backing up to folder: {{ backup_directory }}"

- name: Install pg_dump
  ansible.builtin.apt:
    pkg:
      - postgresql-client-common
      - postgresql-client-14
    state: present

- name: Dump the database to a file
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    port: "{{ postgres_port }}"
    state: dump
    target: /tmp/100eyes-db-dump.gz

- name: Archive storage folder into a single file
  community.general.archive:
    path: /home/ansible/storage
    dest: /tmp/100eyes-storage.tgz

# As for some instances downloading big archives can fail due to not enough memory,
# make archives accessible as non-root user which halfs the necessary memory
# for downloading it.
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html#notes

- name: Archive signal-cli-config folder into a single file
  ansible.builtin.archive:
    path: /home/ansible/signal-cli-config
    dest: /tmp/100eyes-signal-cli-config.tgz

- name: Make backup files read accessible for all users.
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0444'
  with_items:
    - /tmp/100eyes-db-dump.gz
    - /tmp/100eyes-storage.tgz
    - /tmp/100eyes-signal-cli-config.tgz

- name: Download backup files
  fetch:
    src: "{{ item }}"
    dest: "{{ backup_directory }}"
  become: no
  with_items:
    - /tmp/100eyes-db-dump.gz
    - /tmp/100eyes-storage.tgz
    - /tmp/100eyes-signal-cli-config.tgz

- name: Remove backup files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/100eyes-db-dump.gz
    - /tmp/100eyes-storage.tgz
    - /tmp/100eyes-signal-cli-config.tgz
