---
- name: Find /backups
  find:
    paths: backups/
    pattern: '*'
    file_type: directory
  register: backup_directories

- name: Order backup directories
  ansible.builtin.set_fact:
    backup_directories_ordered: "{{ backup_directories.files | sort(attribute='path', case_sensitive=False,reverse=True) }}"

- pause:
    prompt: "{{ lookup('template', './choose_backup_directory.j2') | trim }}"
  register: backup_directory_index

- name: Set backup directory
  set_fact:
    backup_directory: "{{ backup_directories_ordered[(backup_directory_index.user_input | int) - 1] }}"

- name: Find /backups/host
  find:
    paths: "{{ backup_directory.path }}"
    pattern: '*'
    file_type: directory
  register: backup_hosts

- name: Order host directories
  ansible.builtin.set_fact:
    backup_hosts_ordered: "{{ backup_hosts.files | sort(attribute='path', case_sensitive=False,reverse=True) }}"

- pause:
    prompt: "{{ lookup('template', './choose_backup_host.j2') | trim }}"
  register: backup_host_index

- name: Set backup host folder
  set_fact:
    backup_host_folder: "{{ backup_hosts_ordered[(backup_host_index.user_input | int) - 1] }}"
