---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Install passlib required for `password_hash` ansible filter
  import_role:
    name: geerlingguy.pip
    pip_install_packages:
      - name: passlib

- name: Create a new regular user with sudo privileges
  user:
    name: "{{ create_user }}"
    password:  "{{ create_password | password_hash('sha512') }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash
