---
- include_tasks: set_hostname.yml
- include_tasks: packages.yml
- include_tasks: postgresql_client.yml
- include_tasks: ansible_user.yml
- include_tasks: upload_public_keys.yml
- include_tasks: security.yml
