---
- block:
  - name: Set authorized key for remote user
    authorized_key:
      user: "{{ create_user }}"
      state: present
      key: "{{ copy_local_key }}"

  - name: Set additional authorized keys
    authorized_key:
      user: "{{ create_user }}"
      state: present
      key: "{{ lookup('file', item) }}"
    with_items: "{{ copy_additional_keys }}"
  tags: [skip_ci]
