---
- name: Data manipulation to update Setting channels structure
  command:
    cmd: docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec app bin/rails settings:update_channels_default
    chdir: /home/ansible
