postgres_host: "{{ rails.postgres.host | default('db', true) }}"
postgres_db: "{{ rails.postgres.db | default('app_production', true) }}"
postgres_port: "{{ rails.postgres.port | default(5432, true) }}"
postgres_user: "{{ rails.postgres.user }}"
postgres_password: "{{ rails.postgres.password }}"
