#!/bin/bash
# Download, compile and setup Postgresql

install_dir=~/postgres
version=12.2

source_dir=postgresql-${version}
download_path=https://download.postgresql.org/pub/source/v${version}/${source_dir}.tar.gz

host=localhost
port=5432

# Download and extract source
printf "🔷  Downloading source code...\n"
mkdir $install_dir
cd $install_dir
curl -O $download_path
tar -xvzf ${source_dir}.tar.gz
printf "\n✅  Done!\n"

# Compile (including man pages and HTML docs)
printf "\n\n🔷  Compile...\n"
cd $source_dir
./configure --prefix=$HOME/opt/postgresql/
make world
make install-world
printf "\n✅  Done!\n"

# Update bash profile
printf "\n\n🔷  Update bash profile...\n"

cat <<EOT >> ~/.bash_profile
# Postgresql environment
export PATH=$HOME/opt/postgresql/bin/:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/opt/postgresql/lib
export PGPASSFILE=$HOME/.pgpass
EOT

source ~/.bash_profile
printf "\n✅  Done!\n"

# Setup Postgres user
printf "\n\n🔷  Setup Postgres user...\n"
pw=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64)
cat <<EOT >> ~/.pgpass
# hostname:port:database:username:password (min 64 characters)
*:*:*:$(whoami):${pw}
EOT
chmod 0600 ~/.pgpass
printf "\n✅  Done!\n"

# Create database cluster
printf "\n\n🔷  Setup database cluster...\n"
echo $pw > ~/pgpass.temp
initdb --pwfile ~/pgpass.temp --auth=md5 -E UTF8 -D ~/opt/postgresql/data/
rm ~/pgpass.temp
printf "\n✅  Done!\n"

# Setup host and port
printf "\n\n🔷  Setup host and port...\n"
cat <<EOT >> ~/.bashrc
export PGHOST=${host}
export PGPORT=${port}
EOT
source ~/.bashrc
printf "\n✅  Done!\n"

# Adjust configuration
printf "\n\n🔷  Adjust configuration..\n"
config_file=~/opt/postgresql/data/postgresql.conf
sed -i "/#unix_socket_directories.*/iunix_socket_directories = '/home/$(whoami)/tmp'" $config_file
printf "\n✅  Done!\n"

# Setup service
printf "\n\n🔷  Setup service...\n"
cat <<EOT >> ~/etc/services.d/postgresql.ini
[program:postgresql]
command=%(ENV_HOME)s/opt/postgresql/bin/postgres -D %(ENV_HOME)s/opt/postgresql/data/
autostart=yes
autorestart=yes
EOT
supervisorctl reread
supervisorctl update
printf "\n✅  Done!\n"

# Installation summary
printf "\n\n✅  Summary\n"
printf "Version: $(psql --version)\n"
printf "Root Contributor: $(whoami)\n"
printf "Running on ${host}:${port}\n"
