#!/bin/bash

db=app_production
user=app

# Create database and user
printf "\n\n🔷  Create database and user...\n"
pw=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64)
echo "*:*:${db}:${user}:${pw}" >> ~/.pgpass
psql -d $db -c "create role ${user} with login password '${pw}';"
createdb --owner ${user} ${db}
printf "\n✅  Done!\n"

# Setup service
printf "\n\n🔷  Setup service...\n"
cat <<EOT >> ~/etc/services.d/100eyes.ini
[program:100eyes]
directory=$HOME/100eyes
command=bin/bundle exec rails server -b 0.0.0.0
environment=RUBYOPT="-W:no-deprecated",RAILS_ENV=production,RAILS_SERVE_STATIC_FILES=true
autostart=yes
autorestart=yes
EOT
supervisorctl reread
supervisorctl update
printf "\n✅  Done!\n"

# Setup ruby options
printf "\n\n🔷  Setup ruby options...\n"
cat <<EOT >> ~/.bashrc
# Ignore ruby deprecation warnings
export RUBYOPT="-W:no-deprecated"
EOT
source ~/.bashrc
printf "\n✅  Done!\n"

# Setup rails app as web backend
printf "\n\n🔷  Setup rails app as web backend...\n"
uberspace web backend set --http --port 3000 /
printf "\n✅  Done!\n"
