---
roles:
- geerlingguy.docker
- geerlingguy.pip
- gantsign.inotify

collections:
- community.general
### community.docker hotfix version ###
- name: community.docker
  version: 3.10.3
- name: devsec.hardening
