---
logrotate_conf: |
          /home/ansible/log/*.log {
            daily
            missingok
            rotate 7
            compress
            delaycompress
            notifempty
            copytruncate
          }
